services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: akasa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - ./postgres-order:/data/postgres
    ports:
      - "5431:5432"
    restart: unless-stopped

  serviceregistry:
    image: serviceregistry:latest
    container_name: serviceregistry
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  apigateway:
    image: gateway:latest
    container_name: apigateway
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - serviceregistry
      - userservice

  userservice:
    image: userservice:latest
    container_name: userservice
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - serviceregistry

  orderservice:
    image: orderservice:latest
    container_name: orderservice
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - serviceregistry
      - apigateway

  inventoryservice:
    image: inventoryservice:latest
    container_name: inventoryservice
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - serviceregistry
      - apigateway

  cartservice:
    image: cartservice:latest
    container_name: cartservice
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - serviceregistry
      - apigateway
      - inventoryservice
      - userservice
